CFG: 15.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style5/5.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a bridge over a narrow river
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a bridge over a narrow river
output_path: neurips_demo/CFG15.0_sfg10.0_skip10/style5_0_int_0.1/a bridge over a
  narrow river/app=5---struct=6
prompt: a sketch of a bridge over a narrow river
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style5/6.png
struct_name: null
style_image_path: style/style5/7.png
swap_guidance_scale: 10.0
use_masked_adain: false
