name: M3S
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=20.3.3=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==0.20.3
    - anyio==4.5.2
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==25.1.0
    - babel==2.17.0
    - backcall==0.2.0
    - beautifulsoup4==4.13.3
    - bleach==6.1.0
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - click==8.1.8
    - clip-anytorch==2.6.0
    - cmake==3.31.6
    - comm==0.2.2
    - cycler==0.12.1
    - debugpy==1.8.12
    - decorator==5.2.1
    - defusedxml==0.7.1
    - diffusers==0.19.3
    - einops==0.8.1
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastjsonschema==2.21.1
    - filelock==3.16.1
    - fqdn==1.5.1
    - fsspec==2025.2.0
    - ftfy==6.2.3
    - h11==0.14.0
    - h5py==3.11.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.16.4
    - idna==3.10
    - ipykernel==6.29.5
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - json5==0.10.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - lit==18.1.8
    - markupsafe==2.1.5
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - mistune==3.1.2
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - nbclient==0.10.1
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.1
    - nltk==3.8.1
    - notebook==7.3.2
    - notebook-shim==0.2.4
    - numpy==1.20.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-ml-py==12.570.86
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - nvitop==1.4.2
    - overrides==7.7.0
    - packaging==24.2
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==10.1.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.50
    - protobuf==3.20.2
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pygments==2.19.1
    - pyparsing==3.1.4
    - pyrallis==0.3.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.2.1
    - pytz==2025.1
    - pyyaml==6.0.2
    - pyzmq==26.2.1
    - qtconsole==5.6.1
    - qtpy==2.4.3
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.20.1
    - safetensors==0.5.3
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - send2trash==1.8.3
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - sympy==1.13.3
    - tensorboardx==2.6.2.2
    - terminado==0.18.1
    - threadpoolctl==3.5.0
    - timm==1.0.15
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - tomli==2.2.1
    - torch==2.0.1
    - torchvision==0.15.2
    - tornado==6.4.2
    - tqdm==4.64.1
    - traitlets==5.14.3
    - transformers==4.30.2
    - triton==2.0.0
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - uri-template==1.3.0
    - urllib3==2.2.3
    - wcwidth==0.2.13
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.13
    - wrapt==1.17.2
    - xformers==0.0.21
    - zipp==3.20.2
prefix: ~/.conda/envs/M3S
