CFG: 10.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style2/10.PNG
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a seashell on smooth sand
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a seashell on smooth sand
output_path: neurips_demo/CFG10.0_sfg15.0_skip10/style2_0_int_0.1/a seashell on smooth
  sand/app=10---struct=11
prompt: a sketch of a seashell on smooth sand
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style2/11.png
struct_name: null
style_image_path: style/style2/12.png
swap_guidance_scale: 15.0
use_masked_adain: false
