CFG: 17.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/18.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a key lying on a wooden table
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a key lying on a wooden table
output_path: neurips_demo/CFG17.5_sfg17.5_skip10/style3_0_int_0.1/a key lying on a
  wooden table/app=18---struct=19
prompt: a sketch of a key lying on a wooden table
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/19.png
struct_name: null
style_image_path: style/style3/2.PNG
swap_guidance_scale: 17.5
use_masked_adain: false
