CFG: 15.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style2/13.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a mountain peak piercing clouds
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a mountain peak piercing clouds
output_path: neurips_demo/CFG15.0_sfg15.0_skip10/style2_0_int_0.1/a mountain peak
  piercing clouds/app=13---struct=14
prompt: a sketch of a mountain peak piercing clouds
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style2/14.png
struct_name: null
style_image_path: style/style2/15.png
swap_guidance_scale: 15.0
use_masked_adain: false
