CFG: 20.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/18.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: James Bond in a tuxedo and holding a gun
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: James Bond in a tuxedo and holding a gun
output_path: neurips_demo/CFG20.0_sfg10.0_skip10/style3_0_int_0.1/James Bond in a
  tuxedo and holding a gun/app=18---struct=19
prompt: a sketch of James Bond in a tuxedo and holding a gun
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/19.png
struct_name: null
style_image_path: style/style3/2.PNG
swap_guidance_scale: 10.0
use_masked_adain: false
