CFG: 20.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/15.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a hanging lantern at night
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a hanging lantern at night
output_path: neurips_demo/CFG20.0_sfg15.0_skip10/style3_0_int_0.1/a hanging lantern
  at night/app=15---struct=16
prompt: a sketch of a hanging lantern at night
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/16.png
struct_name: null
style_image_path: style/style3/17.png
swap_guidance_scale: 15.0
use_masked_adain: false
