CFG: 15.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style4/12.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a single rose in a slim vase
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a single rose in a slim vase
output_path: neurips_demo/CFG15.0_sfg20.0_skip10/style4_0_int_0.1/a single rose in
  a slim vase/app=12---struct=13
prompt: a sketch of a single rose in a slim vase
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style4/13.png
struct_name: null
style_image_path: style/style4/14.png
swap_guidance_scale: 20.0
use_masked_adain: false
