CFG: 20.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style2/14.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a deer standing in a meadow
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a deer standing in a meadow
output_path: neurips_demo/CFG20.0_sfg20.0_skip10/style2_0_int_0.1/a deer standing
  in a meadow/app=14---struct=15
prompt: a sketch of a deer standing in a meadow
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style2/15.png
struct_name: null
style_image_path: style/style2/16.png
swap_guidance_scale: 20.0
use_masked_adain: false
