CFG: 7.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style2/21.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a cactus in a clay pot
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a cactus in a clay pot
output_path: neurips_demo/CFG7.5_sfg7.5_skip10/style2_0_int_0.1/a cactus in a clay
  pot/app=21---struct=22
prompt: a sketch of a cactus in a clay pot
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style2/22.png
struct_name: null
style_image_path: style/style2/23.png
swap_guidance_scale: 7.5
use_masked_adain: false
