CFG: 7.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style1/5.PNG
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a single feather falling through air
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a single feather falling through air
output_path: neurips_demo/CFG7.5_sfg7.5_skip10/style1_0_int_0.1/a single feather falling
  through air/app=5---struct=6
prompt: a sketch of a single feather falling through air
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style1/6.PNG
struct_name: null
style_image_path: style/style1/7.png
swap_guidance_scale: 7.5
use_masked_adain: false
