CFG: 7.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/20.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a street lamp in light fog
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a street lamp in light fog
output_path: neurips_demo/CFG7.5_sfg7.5_skip10/style3_0_int_0.1/a street lamp in light
  fog/app=20---struct=21
prompt: a sketch of a street lamp in light fog
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/21.png
struct_name: null
style_image_path: style/style3/22.png
swap_guidance_scale: 7.5
use_masked_adain: false
