CFG: 15.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style1/16.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a portrait of naruto
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a portrait of naruto
output_path: neurips_demo/CFG15.0_sfg15.0_skip10/style1_0_int_0.1/a portrait of naruto/app=16---struct=17
prompt: a sketch of a portrait of naruto
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style1/17.png
struct_name: null
style_image_path: style/style1/18.png
swap_guidance_scale: 15.0
use_masked_adain: false
