CFG: 17.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/9.PNG
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a winding river through hills
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a winding river through hills
output_path: neurips_demo/CFG17.5_sfg20.0_skip10/style3_0_int_0.1/a winding river
  through hills/app=9---struct=0
prompt: a sketch of a winding river through hills
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/0.png
struct_name: null
style_image_path: style/style3/1.png
swap_guidance_scale: 20.0
use_masked_adain: false
