CFG: 20.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/9.PNG
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a fox standing on a log
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a fox standing on a log
output_path: neurips_demo/CFG20.0_sfg15.0_skip10/style3_0_int_0.1/a fox standing on
  a log/app=9---struct=0
prompt: a sketch of a fox standing on a log
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/0.png
struct_name: null
style_image_path: style/style3/1.png
swap_guidance_scale: 15.0
use_masked_adain: false
