CFG: 17.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style2/10.PNG
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a cat sitting inside a teacup
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a cat sitting inside a teacup
output_path: neurips_demo/CFG17.5_sfg20.0_skip10/style2_0_int_0.1/a cat sitting inside
  a teacup/app=10---struct=11
prompt: a sketch of a cat sitting inside a teacup
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style2/11.png
struct_name: null
style_image_path: style/style2/12.png
swap_guidance_scale: 20.0
use_masked_adain: false
