CFG: 17.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style3/2.PNG
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a butterfly with plain wings
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a butterfly with plain wings
output_path: neurips_demo/CFG17.5_sfg17.5_skip10/style3_0_int_0.1/a butterfly with
  plain wings/app=2---struct=20
prompt: a sketch of a butterfly with plain wings
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style3/20.png
struct_name: null
style_image_path: style/style3/21.png
swap_guidance_scale: 17.5
use_masked_adain: false
