CFG: 15.0
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style2/0.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: an empty swing hanging from a tree
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: an empty swing hanging from a tree
output_path: neurips_demo/CFG15.0_sfg10.0_skip10/style2_0_int_0.1/an empty swing hanging
  from a tree/app=0---struct=1
prompt: a sketch of an empty swing hanging from a tree
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style2/1.png
struct_name: null
style_image_path: style/style2/10.PNG
swap_guidance_scale: 10.0
use_masked_adain: false
