CFG: 7.5
adain_range:
- 0
- 100
alpha: 0.5
app_image_path: style/style4/16.png
clip_weight: 25
contrast_strength: 1.67
cross_attn_32_range:
- 0
- 70
cross_attn_64_range:
- 0
- 90
domain_name: a winding road through a desert
interpolation: 0.1
load_latents: false
mix_style: true
num_timesteps: 100
object_noun: a winding road through a desert
output_path: neurips_demo/CFG7.5_sfg7.5_skip10/style4_0_int_0.1/a winding road through
  a desert/app=16---struct=17
prompt: a sketch of a winding road through a desert
ref_name: null
reimu: 0.3
resize: false
seed: 42
skip_steps: 10
sparse_weight: 0
struct_image_path: style/style4/17.png
struct_name: null
style_image_path: style/style4/18.png
swap_guidance_scale: 7.5
use_masked_adain: false
